# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7852facdec3e03e81c422e1b27d69bfe2bd3e842bb614327740a7d86cb719a052968d6fa7ed97fa939e59320bac2bd801e4e068d79835314a29f8d2e6f9406

test:
  secret_key_base: 39b647e8b1504d06f8008d48236f7e8d5dc523a91bef27916d2548df229135993fed60c5b473b890fffff6e506b5ece1a02c00208cd844b956b8ef0f4792baa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
